config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
require 'smarter_csv'

class Post < ActiveResource::Base
  self.include_format_in_path = false
  self.site = "https://jsonplaceholder.typicode.com"

  def mediaclip_id
    processed_csv = SmarterCSV.process('static/mapping.csv')

    mediaclips_mapping = processed_csv.map do |mapping| 
      { mapping[:id] => mapping[:mediaclip_id] }
    end.reduce({}, :merge)

    return mediaclips_mapping[id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    set_user
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_user
      @user = params.permit(:user)[:user]
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BbInterviewTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= link_to 'Show', post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @post.id %>
  <strong>Mediaclip_id:</strong>
  <%= @post.mediaclip_id %>
</p>

<script src="https://demo.bbvms.com/launchpad/"></script>

<div id="myPlayerDiv"></div>

<%= link_to 'Back', posts_path %>



<script>

const apiUri = "https://jsonplaceholder.typicode.com/users";

const user = "<%= @user %>" || localStorage.getItem("user_id");
const mediaclipId = "<%= @post.mediaclip_id%>";

let pastFourtyPercent = false;

let myPlayer = new bluebillywig.Player( `https://demo.bbvms.com/p/default/c/${mediaclipId}.json`, {
  target: document.getElementById("myPlayerDiv"),
  autoPlay: "false"
});

const patchUser = (body) => {
  fetch(`${apiUri}/${user}`, {
    method: 'PATCH',
    body: JSON.stringify(body),
    headers: {
      'Content-type': 'application/json; charset=UTF-8',
    },
  })
    .then((response) => response.json())
    .then((json) => console.log(json));
}

const onEnded = () => {
  patchUser({ watchedToEnd: mediaclipId });
};

const onFourtyPercent = () => {
  if(!pastFourtyPercent) {
    pastFourtyPercent = true;

    patchUser({ watchedFourtyPercent: mediaclipId });
  }
};

const onTimeupdate = () => {
  let currentTime = myPlayer.getCurrentTime();
  let maxTime = myPlayer.getDuration();

  if (!pastFourtyPercent && currentTime / maxTime >= 0.4) {
    onFourtyPercent();
  }
}

if (user != null) {
  myPlayer.on('ended', onEnded);
  myPlayer.on('timeupdate', onTimeupdate);
}

myPlayer.play();

</script>